ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Models/Product.cs
namespace WebAppCoreProduct.Models
{
    public class Product
    {
        public string Name { get; set; }
        public decimal? Price { get; set; }
        
    }
}

ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppCoreProduct.Models;

namespace WebAppCoreProduct.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet(string name, decimal? price)
        {
           
        }
        /* Ex1-3
        public Product Product { get; set; }
        public string? MessageRezult { get; set; }
        */

        /* Ex1-2
        public bool IsCorrect { get; set; } = true;
        
        public void OnGet(string name, decimal? price)
        {
            Product = new Product();
            if (price == null || price < 0 || string.IsNullOrEmpty(name))
            {
                IsCorrect = false;
                return;
            }
            Product.Price = price;
            Product.Name = name;

            var result = price * (decimal?)0.18;
            MessageRezult = $"For product {name} with price {price} dicsount is {result}";
        }*/

        /*Ex3
        public void OnGet(string name, decimal? price)
        {
            MessageRezult = "You can have a discount for this product";
        }

        public void OnPost(string name, decimal? price)
        {
            Product = new Product();
            if (price == null || price < 0 || string.IsNullOrEmpty(name))
            {
                MessageRezult = $"Wrong data. Try again";
                return;
            }
            var result = price * (decimal?)0.18;
            MessageRezult = $"For product {name} with price {price} dicsount is {result}";

            Product.Price = price;
            Product.Name = name;
        }
        */
    }
}

ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Pages/Product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppCoreProduct.Models;

namespace WebAppCoreProduct.Pages
{
    public class ProductModel : PageModel
    {
        public Product Product { get; set; }
        public string? MessageRezult { get; set; }

        
        public void OnGet(string name, decimal? price)
        {
            MessageRezult = "You can have a discount for this product";
        }

        public void OnPost(string name, decimal? price)
        {
            Product = new Product();
            if (price == null || price < 0 || string.IsNullOrEmpty(name))
            {
                MessageRezult = $"Wrong data. Try again";
                return;
            }
            var result = price * (decimal?)0.18;
            MessageRezult = $"For product {name} with price {price}$ dicsount is {result}$";

            Product.Price = price;
            Product.Name = name;
        }
        public void OnPostDiscount(string name, decimal? price, double discount)
        {
            Product = new Product();
            var result = price - (price * (decimal?)discount / 100);
            MessageRezult = $"For product {name} with price {price}$ " +
                $"and dicsount {discount}% result price is {result}$";
            Product.Price = price;
            Product.Name = name;
        }
        public void OnPostSaveYourMoney(string name, decimal? price, double discount)
        {
            Product = new Product();
            var result = price - (price - (price * (decimal?)discount / 100));
            MessageRezult = $"For product {name} with price {price}$ " +
                $"and dicsount {discount}% you save {result}$";
            Product.Price = price;
            Product.Name = name;
        }
    }
}

ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Pages/Index.cshtml
@page
@model IndexModel
  
@* Ex4
@{
    Layout = "_Layout";
}
<h3>Start page</h3>
*@

@*  Ex1-3
    <form method="post">
    <label for="name">Product</label><br/>
    <input type="text" name="name"/><br/>
    <label for="price">Price</label><br />
    <input type="number" name="price" /><br />
    <input type="submit" value="Get a dicount" /><br />
</form>

<h3>@Model.MessageRezult</h3>*@

@*  Ex1-2
    @{
    @if(Model.IsCorrect)
    {
        <p>Name: <b>@Model.Product.Name</b></p>
        <p>Price: <b>@Model.Product.Price</b></p>
    }
    else
    {
        <p>Wrong data</p>
    }
    }*@

ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Pages/Product.cshtml
@page "{handler?}"
@model ProductModel
@{
}
<form method="post">
    <label for="name">Product</label><br />
    <input type="text" name="name" /><br />
    <label for="price">Price</label><br />
    <input type="number" name="price" /><br />
    @*<input type="submit" value="Get a discount" /><br />*@
    <input type="submit" asp-page-handler="" value="Get a discount" /><br />

    <label for="discount">Write your discount(%)</label><br />
    <input type="number" name="discount" /><br />

    <input type="submit" asp-page-handler="Discount" value="Price with your discount" /><br />

    <input type="submit" asp-page-handler="SaveYourMoney" value="How much money you can save" /><br />
</form>

<h3>@Model.MessageRezult</h3>

@* Ex4  
    @{
    Layout = "_Layout";
    }
*@

ITMO.ASP.NETCourse2023/ASP.NET Core Razor Pages/Lab1/WebAppCoreProduct/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width"/>
        <title>Razor Pages</title>
    </head>
    <body>
        <div>
            <h1>Account system</h1>
            <div>
                <ul>
                    <li><a asp-page="/Index">Main</a></li>
                    <li><a asp-page="/Product">Product</a></li>
                </ul>
            </div>
            @RenderBody()
        </div>
    <div>&#9400; @DateTime.Now.ToString("dd.MM.yyyy") - Kolmakova Aleksandra</div>
    </body>
</html>